services:
  mongodb-local:
    image: mongo
    container_name: mongodb-local
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_local:/data/db
    restart: always 

volumes:
  mongodb_data_local_tests:
  mongodb_data_local:

